apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: myhamstercage
build:
  artifacts:
  - image: kj7pku/myhamstercage
    context: .
    docker: {}
deploy:
  kubectl:
    manifests:
    - myhamstercage.yaml
